# Generated by Django 5.0.6 on 2024-09-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_delete_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
    ]
